FROM apache/superset

USER root

RUN /app/.venv/bin/python -m ensurepip || true

RUN /app/.venv/bin/python -m pip install --upgrade pip

RUN /app/.venv/bin/python -m pip install psycopg2-binary

USER superset
